### ISSUE TITLE
Ionic Nightly with angular2-moment cannot production build

### ISSUE THREAD

**Issue by dmastag** [urish/angular2-moment#152]
**Description of the Issue and Steps to Reproduce:**

Did you search for duplicate issue? [Yes / No]
Yes

Please describe the issue and steps to reproduce, preferably with a code sample / plunker:

As per https://github.com/ionic-team/ionic-app-scripts/issues/1081
When using this Awesome Package with ionic-app-scripts it breaks the Production Build.
I have prepared a Repo ([ionic-moment--error](https://github.com/dmastag/ionic-moment--error)) to see the problem.

The reason I am posting this is that I am afraid it has something to do with the webpack3 implementation which right not has not been adopted by a lot of users (as per writing this it has not been used by angular-cli either). 

*Ensure your issue is isolated to angular2-moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

**Environment:**

Please answer the following questions:

* Angular version? 4.1.3
* TypeScript version? 2.3.4
* `moment` version? 2.18.1
* Are you using `moment-timezone`? No
* Are you using the angular-cli? No
* Using Rollup/Webpack/System.js/Ionic/similar? Ionic

**Comment by urish** [comment]
Thanks for reporting the issue. How do you reproduce it?

I cloned the repo, npm installed, and then ran `npm run build` and seems like it worked just fine:

```
C:\P\ionic-moment--error>npm run build

> ionic20170706-moment@0.0.1 build C:\P\ionic-moment--error
> ionic-app-scripts build

[10:54:36]  ionic-app-scripts 1.3.12
[10:54:36]  build dev started ...
[10:54:36]  clean started ...
[10:54:36]  clean finished in 5 ms
[10:54:36]  copy started ...
[10:54:36]  transpile started ...
[10:54:40]  transpile finished in 3.58 s
[10:54:40]  preprocess started ...
[10:54:40]  deeplinks started ...
[10:54:40]  deeplinks finished in 16 ms
[10:54:40]  preprocess finished in 20 ms
[10:54:40]  webpack started ...
[10:54:40]  copy finished in 4.08 s
[10:54:51]  webpack finished in 11.27 s
[10:54:51]  sass started ...
[10:54:53]  sass finished in 1.57 s
[10:54:53]  postprocess started ...
[10:54:53]  postprocess finished in 31 ms
[10:54:53]  lint started ...
[10:54:53]  build dev finished in 16.57 s
[10:55:06]  lint finished in 13.35 s
```

**Comment by dmastag** [comment]
Hi @urish ,
Its needs to be a production build so `npm run build --prod` and then the problem happens.
Thanks for looking into this.

Julian

**Comment by urish** [comment]
thanks @dmastag , still works fine:

```
C:\P\ionic-moment--error>npm run build --prod

> ionic20170706-moment@0.0.1 build C:\P\ionic-moment--error
> ionic-app-scripts build

[15:28:55]  ionic-app-scripts 1.3.12
[15:28:55]  build prod started ...
[15:28:55]  clean started ...
[15:28:55]  clean finished in 6 ms
[15:28:55]  copy started ...
[15:28:55]  ngc started ...
[15:29:00]  ngc finished in 5.37 s
[15:29:00]  preprocess started ...
[15:29:00]  deeplinks started ...
[15:29:00]  deeplinks finished in 32 ms
[15:29:00]  optimization started ...
[15:29:00]  copy finished in 5.62 s
[15:29:12]  optimization finished in 12.18 s
[15:29:12]  preprocess finished in 12.21 s
[15:29:12]  webpack started ...
[15:30:55]  webpack finished in 102.52 s
[15:30:55]  sass started ...
[15:30:55]  uglifyjs started ...
[15:30:56]  sass finished in 841 ms
[15:30:56]  cleancss started ...
[15:30:57]  cleancss finished in 1.31 s
[15:31:06]  uglifyjs finished in 10.94 s
[15:31:06]  postprocess started ...
[15:31:06]  postprocess finished in 13 ms
[15:31:06]  lint started ...
[15:31:06]  build prod finished in 131.11 s
[15:31:13]  lint finished in 6.60 s
```

Can you post your output so we can compare?

**Comment by dmastag** [comment]
I am getting the following

npm run build --prod

> ionic20170706-moment@0.0.1 build D:\GM Work Box\playground\ionic20170706-moment
> ionic-app-scripts build

[23:49:48]  ionic-app-scripts 1.3.12-201707060514
[23:49:48]  build prod started ...
[23:49:48]  clean started ...
[23:49:48]  clean finished in 5 ms
[23:49:48]  copy started ...
[23:49:48]  ngc started ...
[23:49:55]  ngc finished in 6.43 s
[23:49:55]  preprocess started ...
[23:49:55]  deeplinks started ...
[23:49:55]  deeplinks finished in 36 ms
[23:49:55]  optimization started ...
[23:49:55]  copy finished in 7.14 s
[23:50:03]  optimization finished in 8.40 s
[23:50:03]  preprocess finished in 8.59 s
[23:50:03]  webpack started ...
[23:51:13]  webpack finished in 70.08 s
[23:51:13]  sass started ...
[23:51:14]  uglifyjs started ...
[23:51:14]  ionic-app-script task: "build"
[23:51:14]  Error: ENOENT: no such file or directory, scandir 'D:\GM Work
            Box\playground\ionic20170706-moment\node_modules\moment\locale \^'
Error: ENOENT: no such file or directory, scandir 'D:\GM Work Box\playground\ionic20170706-moment\node_modules\moment\locale \^'
    at Object.fs.readdirSync (fs.js:909:18)
    at getSiblingSassFiles (D:\GM Work Box\playground\ionic20170706-moment\node_modules\@ionic\app-scripts\dist\sass.js:155:23)
    at addComponentSassFiles (D:\GM Work Box\playground\ionic20170706-moment\node_modules\@ionic\app-scripts\dist\sass.js:132:24)
    at D:\GM Work Box\playground\ionic20170706-moment\node_modules\@ionic\app-scripts\dist\sass.js:127:9
    at Array.forEach (native)
    at getComponentSassFiles (D:\GM Work Box\playground\ionic20170706-moment\node_modules\@ionic\app-scripts\dist\sass.js:126:26)
    at generateSassData (D:\GM Work Box\playground\ionic20170706-moment\node_modules\@ionic\app-scripts\dist\sass.js:111:30)
    at D:\GM Work Box\playground\ionic20170706-moment\node_modules\@ionic\app-scripts\dist\sass.js:71:13
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic20170706-moment@0.0.1 build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic20170706-moment@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\julia\AppData\Roaming\npm-cache\_logs\2017-07-07T16_51_14_149Z-debug.log

**Comment by dmastag** [comment]
Could be working for you since you are on the newest nightly (should have save-exact).
There is an update on the Ionic Issue, let me see how that works.

https://github.com/ionic-team/ionic-app-scripts/issues/971#issuecomment-313724394

**Comment by dmastag** [comment]
Still not working with the latest nightly (I updated the package also)

```
D:\GM Work Box\playground\ionic20170706-moment>npm run build --prod

> ionic20170706-moment@0.0.1 build D:\GM Work Box\playground\ionic20170706-moment
> ionic-app-scripts build

[00:24:25]  ionic-app-scripts 1.3.12-201707071538
[00:24:25]  build prod started ...
[00:24:25]  clean started ...
[00:24:25]  clean finished in 3 ms
[00:24:25]  copy started ...
[00:24:25]  ngc started ...
[00:24:30]  ngc finished in 4.62 s
[00:24:30]  preprocess started ...
[00:24:30]  deeplinks started ...
[00:24:30]  deeplinks finished in 22 ms
[00:24:30]  optimization started ...
[00:24:30]  copy finished in 4.89 s
[00:24:37]  optimization finished in 7.70 s
[00:24:37]  preprocess finished in 7.83 s
[00:24:37]  webpack started ...
[00:25:46]  webpack finished in 68.85 s
[00:25:46]  sass started ...
[00:25:46]  uglifyjs started ...
[00:25:46]  ionic-app-script task: "build"
[00:25:46]  Error: ENOENT: no such file or directory, scandir 'D:\GM Work
            Box\playground\ionic20170706-moment\node_modules\moment\locale \^'
Error: ENOENT: no such file or directory, scandir 'D:\GM Work Box\playground\ionic20170706-moment\node_modules\moment\locale \^'
    at Object.fs.readdirSync (fs.js:909:18)
    at getSiblingSassFiles (D:\GM Work Box\playground\ionic20170706-moment\node_modules\@ionic\app-scripts\dist\sass.js:155:23)
    at addComponentSassFiles (D:\GM Work Box\playground\ionic20170706-moment\node_modules\@ionic\app-scripts\dist\sass.js:132:24)
    at D:\GM Work Box\playground\ionic20170706-moment\node_modules\@ionic\app-scripts\dist\sass.js:127:9
    at Array.forEach (native)
    at getComponentSassFiles (D:\GM Work Box\playground\ionic20170706-moment\node_modules\@ionic\app-scripts\dist\sass.js:126:26)
    at generateSassData (D:\GM Work Box\playground\ionic20170706-moment\node_modules\@ionic\app-scripts\dist\sass.js:111:30)
    at D:\GM Work Box\playground\ionic20170706-moment\node_modules\@ionic\app-scripts\dist\sass.js:71:13
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic20170706-moment@0.0.1 build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic20170706-moment@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\julia\AppData\Roaming\npm-cache\_logs\2017-07-07T17_25_46_922Z-debug.log
```

**Comment by urish** [comment]
According to the stack trace, it seems like the Ionic `app-scripts` package
is having trouble with scanning the package directory of `moment` while
looking for sass files.

```
Error: ENOENT: no such file or directory, scandir 'D:\GM Work
Box\playground\ionic20170706-moment\node_modules\moment\locale \^'

    at Object.fs.readdirSync (fs.js:909:18)
    at getSiblingSassFiles (D:\GM Work
Box\playground\ionic20170706-moment\node_modules\@ionic\app-scripts\dist\sass.js:155:23)

```


I'd suggest opening an issue for Ionic app-scripts about this.


On 7 Jul 2017 8:27 PM, "Julian Alimin" <notifications@github.com> wrote:

Still not working with the latest nightly (I updated the package also)

D:\GM Work Box\playground\ionic20170706-moment>npm run build --prod

> ionic20170706-moment@0.0.1 build D:\GM Work Box\playground\ionic20170706-moment
> ionic-app-scripts build

[00:24:25]  ionic-app-scripts 1.3.12-201707071538
[00:24:25]  build prod started ...
[00:24:25]  clean started ...
[00:24:25]  clean finished in 3 ms
[00:24:25]  copy started ...
[00:24:25]  ngc started ...
[00:24:30]  ngc finished in 4.62 s
[00:24:30]  preprocess started ...
[00:24:30]  deeplinks started ...
[00:24:30]  deeplinks finished in 22 ms
[00:24:30]  optimization started ...
[00:24:30]  copy finished in 4.89 s
[00:24:37]  optimization finished in 7.70 s
[00:24:37]  preprocess finished in 7.83 s
[00:24:37]  webpack started ...
[00:25:46]  webpack finished in 68.85 s
[00:25:46]  sass started ...
[00:25:46]  uglifyjs started ...
[00:25:46]  ionic-app-script task: "build"
[00:25:46]  Error: ENOENT: no such file or directory, scandir 'D:\GM Work
            Box\playground\ionic20170706-moment\node_modules\moment\locale \^'
Error: ENOENT: no such file or directory, scandir 'D:\GM Work
Box\playground\ionic20170706-moment\node_modules\moment\locale \^'
    at Object.fs.readdirSync (fs.js:909:18)
    at getSiblingSassFiles (D:\GM Work
Box\playground\ionic20170706-moment\node_modules\@ionic\app-scripts\dist\sass.js:155:23)
    at addComponentSassFiles (D:\GM Work
Box\playground\ionic20170706-moment\node_modules\@ionic\app-scripts\dist\sass.js:132:24)
    at D:\GM Work
Box\playground\ionic20170706-moment\node_modules\@ionic\app-scripts\dist\sass.js:127:9
    at Array.forEach (native)
    at getComponentSassFiles (D:\GM Work
Box\playground\ionic20170706-moment\node_modules\@ionic\app-scripts\dist\sass.js:126:26)
    at generateSassData (D:\GM Work
Box\playground\ionic20170706-moment\node_modules\@ionic\app-scripts\dist\sass.js:111:30)
    at D:\GM Work
Box\playground\ionic20170706-moment\node_modules\@ionic\app-scripts\dist\sass.js:71:13
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic20170706-moment@0.0.1 build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic20170706-moment@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\julia\AppData\Roaming\npm-cache\_logs\2017-07-07T17_25_46_922Z-debug.log

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/urish/angular2-moment/issues/152#issuecomment-313744017>,
or mute the thread

**Comment by dmastag** [comment]
Thanks @urish appreciate you looking into this.
Will contact them about this and hopefully get a solution.
